### ISSUE TITLE
Can false finding not be displayed in the report? 

### ISSUE THREAD

**Issue by HTQianqian** [Fraunhofer-AISEC/codyze#107]
TestCode:
1 package WeakEncryption.InadequateRSAPadding;
2
3 import javax.crypto.Cipher;
4
5 public class CWE780_WeakEncryption_InadequateRSAPadding_01 {
6 public void bad() throws Exception {
7 /* POTENTIAL FLAW: Not OAEP */
8 Cipher.getInstance("RSA");
9 }
10
11 public void good() throws Exception {
12 Cipher.getInstance("RSA/ECB/OAEPWithSHA-512AndMGF1Padding");
13 }
14 }

The findings.json contains false problem (which the problem property is false) and true problem (which the problem property is true). Is there a way to hide the false problem findings? In this way, we check efficiency will be improved.

**Comment by agigleux** [comment]
I believe you can achieve that with the "--no-good-findings" on the Codyze CLI.

> --no-good-findings    Disable output of "positive" findings which indicate correct implementations
