### ISSUE TITLE
C++ temporaries are not resolved via ConstructExpressions

### ISSUE THREAD

**Issue by JulianSchuette** [Fraunhofer-AISEC/codyze#11]
With the following Java code, the constant resolver determines the value of the algorithm ("I AM INCORRECT..."):
```
PK_Verifier sig_verifier = new PK_Verifier(new RSA_PublicKey(id, 123), "I AM INCORRECT EMSA4(SHA-256)");
```  

With C++, similar code cannot be resolved:
```
Botan::PK_Verifier sig_verifier(Botan::PubKey(id, 123), "I AM INCORRECT EMSA4(SHA-256)");
```

**Comment by JulianSchuette** [comment]
Here are test cases demonstrating the problem: 7177da6655a9feae18b15d22b95909e5bf1c0df6

**Comment by fwendland** [comment]
The call to `Botan::PubKey(id, 123)` is parsed as a `FunctionCallExpression`. In the CPG it becomes a `CallExpression`. The MARK evaluator in codyze expects a `DeclaredReferenceExpression` or a `Literal`.

It seems to be a combination of a possible mislabeling by the CDT parser and an incomplete case handling by the crymlin query evaluator. I'm going to follow this lead.
