### ISSUE TITLE
eclipse plugin not existed ：https://update.breakpoint-security.de

### ISSUE THREAD

**Issue by niuzhi** [Fraunhofer-AISEC/codyze#12]
![image](https://user-images.githubusercontent.com/33443724/84988757-2186e500-b175-11ea-9dea-10710d549ea1.png)

**Comment by fwendland** [comment]
Hi niuzhi,

Sorry for not coming back to you earlier. I'm going to take a look why the repository isn't working. Please trigger me again if I haven't replied in a couple of days.

**Comment by JulianSchuette** [comment]
Please use the URL https://update.breakpoint-security.com
