### ISSUE TITLE
Heisenbug in tests

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/codyze#143]
Looks like this is still an issue to some degree:

```
RealBCTest > testSimple() FAILED
    java.util.concurrent.ExecutionException at RealBCTest.java:20
        Caused by: java.lang.StackOverflowError at Class.java:1550
```

_Originally posted by @oxisto in https://github.com/Fraunhofer-AISEC/codyze/issues/32#issuecomment-769903418_

**Comment by fwendland** [comment]
I have seen it as well. I thought that it was due to some left over files or not fully synced tests. Apparently, I was wrong :(

**Comment by fwendland** [comment]
Haven't seen this one in a while. Assuming it has been fixed potentially with our move towards v3.
