### ISSUE TITLE
The analysis process is very slow

### ISSUE THREAD

**Issue by tiandiyixian** [Fraunhofer-AISEC/codyze#19]
Hi,
    I randomly detect  a few open source projects, but found that the analysis process is very very slow, and no results have been produced, nor do I know how long it will produce results, whether there are some optimization measures, or command parameters to fast?this is a random project I use the command ,./Codyze -c -s=/root/WebGoat5.0 -m=/root/codyze/src/test/resources/mark_java, at the earliest time./codyze -c --typestate NFA --interproc -s=/ root/WebGoat5.0 -m=/root/codyze/src/test/resources/mark_java, but they are both very slow, have not been completed, the test was initiated at night, and there was no result in the morning,

**Comment by fwendland** [comment]
Hi tiandiyixian,

Can you send me a link to the `WebGoat5.0` project?

It's very difficult to give you useful advice without having some idea what your trying to analyze.

**Comment by JulianSchuette** [comment]
Hi tiandiyixian!

Neither Codyze nor CPG have been optimized for performance until now, so there is definitely room for improvement. Having said that, running the analysis all night without getting results sounds like a bug and if you provide the GitHub link, we will check what is wrong here.

We did a rough performance estimate on ~1400 Github projects. As you can see in the diagram, the majority of files (not projects) is well below 2 seconds, the median is somewhere 700ms-ish.

![performance_2d](https://user-images.githubusercontent.com/1555755/86356145-08e5f700-bc6c-11ea-9839-8afb7e32216b.png)

**Comment by tiandiyixian** [comment]
@fwendland 
Hi  fwendland ,
                Thanks for your reply. This is my test case.:https://github.com/11112222/WebGoat5_0_32555lines/tree/master/WebGoat5.0. It ran for a long time when analyzing it, or the process was a memory leak and  exit. After increasing the memory, it was a long wait.

**Comment by tiandiyixian** [comment]
@JulianSchuette 
Thanks  for your reply, maybe my test cases are special cases, webgoat 5.0 and OWASP benchmark, both of them have been analyzed for a long time without results, I will try other use cases

**Comment by JulianSchuette** [comment]
I am closing this since the upgrade to `cpg 2.1.1` many things have changed and improved. However, there is still a bug (#32) in the deserialization module that needs to be fixed. When that is done, we will repeat the performance evaluation.
