### ISSUE TITLE
Cannot use Codyze in Windows 10

### ISSUE THREAD

**Issue by shahrzadav** [Fraunhofer-AISEC/codyze#203]
I tried installing Codyze on Eclipse 2020-09, Intellij 2020.3.1, and Visual Studio 2019 with Java 11, but none of them show the result of Codyze's analysis. I could only use Codyze (see the result of analysis) in Eclipse 2020-09 on Ubuntu 20.04.1 LTS. I followed the steps as it is on Codyze documentation page.

**Comment by fwendland** [comment]
Hi @shahrzadav,

there seems to be a problem with one of the type state analysis methods. By default, we're using one analysing the whole program. This analysis should be more acurate. However, there seems to be a long running task/loop. Hence, no results are posted back and it seems like Codyze isn't working.

As a intermediate fix you can change the type state analysis in the preferences to _Within functions only_.

**Comment by shahrzadav** [comment]
Hi @fwendland, 
Thanks for your response. I changed the type state analysis to Within functions only in the preference page of Eclipse 2019-06 but, I still do not see the result of the analysis. I analyzed the same file in Codyze CLI mode, and I get the misuses, but I see no results in the IDE.

**Comment by fwendland** [comment]
Hi @shahrzadav 

I think, Eclipse 2019-06 is to old. I just downloaded it and tried to install the plugin. However, the installation failed because the LSP4E dependency couldn't be resolved.

Can you please try a newer version like 2020-06 or 2021-03?

**Comment by fwendland** [comment]
Hi @shahrzadav 

Any success with a newer version of Eclipse?

**Comment by shahrzadav** [comment]
Hi @fwendland, sorry for the late reply. Yes, I was able to get the result of the analysis by Codyze in Eclipse 2020-09. Thank you.

**Comment by fwendland** [comment]
You're welcome, I'm closing this issue for now. Feel free to open a new one when you come across more problems :)
