### ISSUE TITLE
codyze CLI mode error

### ISSUE THREAD

**Issue by niuzhi** [Fraunhofer-AISEC/codyze#23]
codyze CLI mode run query command，Prompt "query" or “q” is not defined。
![image](https://user-images.githubusercontent.com/33443724/86780656-8efca600-c08f-11ea-923b-eea01c0fe9df.png)

**Comment by JulianSchuette** [comment]
It appears you are using the version 1.0.0. Codyze is still under rapid development and the release is outdated.

Please use the latest `master` version for now:

```
git clone https://github.com/Fraunhofer-AISEC/codyze.git
./gradlew installDist
./build/install/codyze -t
```
