### ISSUE TITLE
codeyz contribution

### ISSUE THREAD

**Issue by niuzhi** [Fraunhofer-AISEC/codyze#24]
codeyz dev:
  I am very interested in CPG and codyze. At present, there are not many practical examples in the documentation. Can you provide examples of data flow query? In addition, how to join the codyze community for co-creation development? In terms of theoretical research, are there any outstanding topics? Thank you!

**Comment by JulianSchuette** [comment]
Thank you for your interest in the project! Please contact me at _julian.schuette [at] aisec.fraunhofer.de_ for further discussion.
