### ISSUE TITLE
Codyze api document！

### ISSUE THREAD

**Issue by niuzhi** [Fraunhofer-AISEC/codyze#25]
Hello：
  Codyze dev：
     Is there an API document for Codyze? In the absence of documentation, the following methods cannot be used quickly。
     For example：flowFrom()  、flowTo()、how to use？thanks
![image](https://user-images.githubusercontent.com/33443724/86903661-3b976000-c142-11ea-810f-8c5627cee9a0.png)

**Comment by JulianSchuette** [comment]
Hi there!

95% of these operations are standard "Apache Gremlin" language. The documentation is found here: https://tinkerpop.apache.org/docs/current/reference/#traversal

The other operations are explained in the [JavaDoc of CrymlinTraversalSourceDSL](https://github.com/Fraunhofer-AISEC/codyze/blob/6e0d834a09ebaa72a34bab2c25c390bddf5102b7/src/main/java/de/fraunhofer/aisec/crymlin/dsl/CrymlinTraversalSourceDsl.java). We are working on a way to make it more accessible, either by including it in the documentation at www.codyze.io or by publishing the JavaDocs separately.

Btw, the blue/violet operations are "discouraged". They are internal Java/Gremlin methods you most likely won't need in the console.

**Comment by JulianSchuette** [comment]
The documentation at codyze.io as well as the `help()` command in the console has been updated.
