### ISSUE TITLE
Errors found by Codyze do not turn red.

### ISSUE THREAD

**Issue by shahrzadav** [Fraunhofer-AISEC/codyze#285]
I built Codyze project from the main branch and I use it in Eclipse to detect misuses. But now the error and verify markers appear the same and the errors do not turn red. I also cannot see the errors in the problem tab.

<img width="520" alt="Untitled" src="https://user-images.githubusercontent.com/7203009/134659363-480451f2-9ceb-4b7e-9620-e20a266a0418.png">

**Comment by fwendland** [comment]
Hi Shahrzadav,

thank you for finding this one. I just saw it myself. I need to go looking for the problem.

**Comment by fwendland** [comment]
We're no longer supporting our Codyze plugin for Eclipse.
