### ISSUE TITLE
Trouble using Codyze on IntelliJ

### ISSUE THREAD

**Issue by shahrzadav** [Fraunhofer-AISEC/codyze#374]
I faced an issue when I was trying to install Codyze on IntelliJ. I followed the steps on the Codyze doc page to install Codyze on IntelliJ. I maintained a connection to the language server (the green light), but I do not see the analysis result on my editor or the problem tool window. Are there any other steps that I need to do to get the results?
Also, the crymlin.log file is empty.

**Comment by fwendland** [comment]
We removed LSP support in favor of hjust using SARIF and potential IDE plugins, that can automatically pick up new SARIF files and display their findings.
