### ISSUE TITLE
Windows Path Issues for ConfigLoadTest

### ISSUE THREAD

**Issue by CodingDepot** [Fraunhofer-AISEC/codyze#536]
When using Windows, the _pathsTest_ in _ConfigLoadTest.kt_ fails with:
`org.opentest4j.AssertionFailedError: Iterable elements differ at index 0. Expected element <D:\absolute\path\to\source>, actual element <D:\Fraunhofer_AISEC\codyze\codyze-v2\build\resources\test\config-files\absolute\path\to\source>.
`

This problem - that the absolute path component is appended - seems to occur in Windows systems only.

I opened this Issue since it is not clear whether this problem affects this specific test case only or if the implementation of the configuration parsing suffers from the same issue.

**Comment by seelchen** [comment]
I think I solved the problem, could you test it again and see if it works now?

**Comment by CodingDepot** [comment]
Yes, #557 seems to fix this. All tests are passing now. 👍
