### ISSUE TITLE
Consistent versioning scheme for v3

### ISSUE THREAD

**Issue by fwendland** [Fraunhofer-AISEC/codyze#548]
With v3 we separated Codyze into at least 3 modules:

- `codyze-core` for managing project resources and configuring central components (i.e CPG, spec language executor)
- `codyze` for an application with CLI
- `codyze-specification-language` for implementations of executors that evaluate a specific spec language such as MARK

These modules can have a common version or distinct versions. 

- What are use cases for either? 
- What are modules that should have the same version?
- How do we configure Gradle to enforce our version policy?

**Comment by oxisto** [comment]
Don't overcomplicate it. Keep the version the same across the submodules.
