### ISSUE TITLE
Enable maven publish for v3 artefacts

### ISSUE THREAD

**Issue by fwendland** [Fraunhofer-AISEC/codyze#554]
Extend Gradle to support publishing Maven artefacts for other projects to consume v3 libraries.

**Comment by oxisto** [comment]
I assume you are talking about Maven Central? Is there any particular use case for this? For now we have seen Codyze primarily as a tool and not as a library. In the very few cases we needed it as a library, jitpick served quite well. 

Publishing to maven central is a major pain and I would strongly think twice about doing it, if its not necessary.

**Comment by fwendland** [comment]
It's not about Maven Central. I should have been more specific.

I use Codyze v2 as a library in other projects using JitPack to consume it. As far as I can see, this doesn't work for v3 because there isn't a Gradle task to build an artifact for a Maven repo.

We just need to add this task/plugin wiothout actually configuring a publication/upload to Maven Central.
