### ISSUE TITLE
Generate AST for C/C++ Source

### ISSUE THREAD

**Issue by VenoVeno** [Fraunhofer-AISEC/codyze#712]
Hi,
I would like use Codyze as a C/C++ Source parser to convert it to AST. Is it possible to construct a AST or Parse Tree using Codyze?

**Sample**
```
#include <stdio.h>

int main()
{
    printf("Hello World");

    return 0;
}
```

**Expected Output:**
```
- FunctionDefinition int main(){    printf("Hello World");    return 0;}
  - SimpleDeclSpecifier int
  - FunctionDeclarator main()
    - Name main
  - CompoundStatement {    printf("Hello World");    return 0;}
    - ExpressionStatement printf("Hello World");
      - FunctionCallExpression printf("Hello World")
        - IdExpression printf
          - Name printf
        - LiteralExpression "Hello World"
    - ReturnStatement return 0;
      - LiteralExpression 0 
```

Thanks.

**Comment by seelchen** [comment]
Hello, this is not possible with Codyze. 
You could take a look at the [CPG project](https://github.com/Fraunhofer-AISEC/cpg) which builds the AST among other things. However, the output of the CPG is not really similar to the expected output you gave.
