### ISSUE TITLE
Upgrade to OverflowDB v1.x

### ISSUE THREAD

**Issue by fwendland** [Fraunhofer-AISEC/codyze#85]
OverflowDB has gone through some development iterations. The current version is v1.x. We're using the 0.x build.

Should we invest the work to upgrade to 1.x?

**Comment by fwendland** [comment]
@oxisto 

Do we still want to update OverflowDB?

**Comment by oxisto** [comment]
I would rather get rid of it completely and rely on the in-memory representation of the CPg.

**Comment by fwendland** [comment]
Ok, opening up a new issue.
