### ISSUE TITLE
Plugins for IntelliJ and VSCode

### ISSUE THREAD

**Issue by oxisto** [Fraunhofer-AISEC/codyze#92]
Would be nice, since both have a greater "market share" than eclipse.

**Comment by fwendland** [comment]
@oxisto 

Did you look into support for IntelliJ and VC Code?

**Comment by fwendland** [comment]
- [x] VSCode (#265)
- [ ] IntelliJ

**Comment by fwendland** [comment]
@oxisto Are we still planing a plugin for IntelliJ? Or are we using the generic LSP plugin (https://plugins.jetbrains.com/plugin/10209-lsp-support)?

**Comment by fwendland** [comment]
We currently have no plans to support LSP. We've moved to SARIF and IDEs are free to interpret the generated SARIF file by Codyze.
